export const DUMMY_PRODUCTS = {
        "Computers and Accessories":[
            {
                id:'Computers and Accessories_1',
                title: 'Lenovo IdeaCentre A340',
                rating: 4,
                img: 'https://impressivenotebook.com/wp-content/uploads/2020/09/Lenovo-IdeaCentre-AIO-3i-F0EU0033US.jpg',
                price: 499,
                inStock: true,
                keywords: 'computer computers cpu processors processor',
                description: 'With its sleek, modern stand and thin bezel display, the IdeaCentre A340 is designed to catch the eye. Fire it up and marvel at the way it handles everything with ease, quickly and smoothly. Even with the space-saving design, it can store plenty, too. This all-in-one makes the ideal home PC.',
            },
            {
                id:'Computers and Accessories_2',
                title: 'Dell Optiplex 790',
                rating: 4,
                img: 'https://i.dell.com/sites/csimages/Video_Imagery/all/optiplex-aio-thumbnail.png',
                price: 299,
                inStock: true,
                keywords: 'computer computers cpu processors processor',
                description: 'All Amazon Renewed purchases will come with accessories that may be not be original, but will be compatible and fully functional. Amazon Renewed ducts will be packaged in either original packaging or in a new and clean cardboard box. duct will be clean and may have a few visible signs of earlier use.',
            },
            {
                id:'Computers and Accessories_3',
                title: 'Zebronics Slim',
                rating: 5,
                img: 'https://images-na.ssl-images-amazon.com/images/I/71vNrx05QFL._SL1500_.jpg',
                price: 229,
                inStock: true ,
                keywords: 'computer computers cpu processors processor',
                description: 'Zebronics Slim Desktop Computer Intel Core i3-4130 /8GB RAM / 500GB HDD/WiFi Ready 19" HD Led Monitor with Keyboard Mouse',
            },
            {
                id:'Computers and Accessories_4',
                title: 'Ant Esports',
                rating: 4,
                img: 'https://i2.wp.com/nakodaithub.com/wp-content/uploads/2021/03/61WhHoPNAlL._SL1080_.jpg?fit=1080%2C1080&ssl=1',
                price: 299,
                inStock: true ,
                keywords: 'computer computers cpu processors processor',
                description: 'Ant Esports ICE-130AG Mid Tower Computer Case I Gaming Cabinet Supports ATX, Micro-ATX, Mini-ITX Motherboard with 1 x 120 mm Rear Fan Preinstalled - Black',
            },
            {
                id:'Computers and Accessories_5',
                title: 'ZEBRONICS Zeb-Warrior',
                rating: 4,
                img: 'https://images-na.ssl-images-amazon.com/images/I/81grtcmxsyL._SL1500_.jpg',
                price: 6,
                inStock: true ,
                keywords: 'speakers',
                description: 'Revolutionizing technology for the masses, incorporating Excellence, Quality and Reliability in products range, be it Soundbars, Home Theatres, Headphones, Earphones, TWS, Gaming Cabinets',
            },
            {
                id:'Computers and Accessories_6',
                title: 'Logitech C270',
                rating: 5,
                img: 'https://images-na.ssl-images-amazon.com/images/I/61yo4swj-PL._SY450_.jpg',
                price: 29,
                inStock: true ,
                keywords: 'webcam camera webcams cameras',
                description: 'The Logitech C270 HD Webcam makes video calling seamless, compatible with PC, Mac and ChromeOS platforms - as well as Skype, Google Hangouts and FaceTime.',
            },
            {
                id:'Computers and Accessories_7',
                title: 'SanDisk Cruzer',
                rating: 5,
                img: 'https://www.kindpng.com/picc/m/592-5922361_pen-drive-sandisk-8gb-png-sandisk-cruzer-blade.png',
                price: 3,
                inStock: true ,
                keywords: 'pendrive pendrives flashdrives storage memory externaldrive',
                description: 'The SanDisk 16GB Cruzer Blade USB Flash Drive from SanDisk is a compact, portable USB flash drive. It allows you to carry and transfer files on the go like photos, videos or music',
            },
            {
                id:'Computers and Accessories_8',
                title: 'SanDisk Ultra',
                rating: 5,
                img: 'https://images-na.ssl-images-amazon.com/images/I/71bV203ASmL._SL1500_.jpg',
                price: 5,
                inStock: true ,
                keywords: 'pendrive pendrives flashdrives storage memory externaldrive',
                description: 'The SanDisk Ultra Dual Drive m3.0 makes it easy to transfer content from your phone to your computer.',
            },
            {
                id:'Computers and Accessories_9',
                title: 'Lenovo IdeaPad',
                rating: 3,
                img: 'https://www.notebookcheck.net/fileadmin/Notebooks/News/_nc3/ideapad.jpeg',
                price: 830,
                inStock: true ,
                keywords: 'laptops laptop',
                description: 'The new Lenovo IdeaPad™ 5i boasts an enticing list of features, making it a powerful combination of performance, connectivity, and entertainment with 11th Generation Intel® Core™ processors.',
            },
            {
                id:'Computers and Accessories_10',
                title: 'ASUS VivoBook 14',
                rating: 4,
                img: 'https://www.notebookcheck.net/fileadmin/Notebooks/Asus/VivoBook_14_X412FJ-EB023T/4zu3_Asus_Vivobook_14_X412FJ.jpg',
                price: 240,
                inStock: true ,
                keywords: 'laptops laptop',
                description: 'ASUS VivoBook 14 is the entry-level laptop that delivers powerful performance and immersive visuals. Its NanoEdge display and a matte anti-glare coating for a truly engaging experience.',
            },
            {
                id:'Computers and Accessories_11',
                title: 'Apple MacBook Air',
                rating: 5,
                img: 'https://i.pinimg.com/originals/c5/06/d9/c506d9ebf0629039d9a81c90dcb9b42c.jpg',
                price: 883,
                inStock: true ,
                keywords: 'laptops laptop',
                description: 'The incredibly thin and light MacBook Air features a brilliant Retina display with True Tone techology',
            },
            {
                id:'Computers and Accessories_12',
                title: 'Sony WH-XB900N',
                rating: 5,
                img: 'https://mk0soundguyshosprmrt.kinstacdn.com/wp-content/uploads/2019/07/Sony-WHXB900N-6.jpg',
                price: 169,
                inStock: true ,
                keywords: 'headphones earphones headphone earphone',
                description: 'The WH-XB900N is Wireless Extra Bass and Noise Cancellation Headphones with Quick Attention Mode, Touch Sensor, Sense Engine and Built-In Alexa. Hear e bass and don’t let the noise stop you.',
            },
            {
                id:'Computers and Accessories_13',
                title: 'HyperX Keyboard',
                rating: 5,
                img: 'https://media.kingston.com/hyperx/product/hx-product-keyboard-alloy-origins-us-1-zm-lg.jpg',
                price: 89,
                inStock: true ,
                keywords: 'keyboard mechanicalkeyboard',
                description: 'The HyperX Alloy Origins Core is an ultra-compact, sturdy tenkeyless keyboard featuring custom HyperX mechanical switches designed to give gamers the best blend of style, performance, and reliability.',
            },
            {
                id:'Computers and Accessories_14',
                title: 'Razer DeathAdder',
                rating: 5,
                img: 'https://i.pinimg.com/originals/1a/17/73/1a177399a534dbd3cbe37e2ea35d5ada.jpg',
                price: 58,
                inStock: true ,
                keywords: 'mouse mouses opticalmouse',
                description: 'With over 10 million Razer DeathAdders sold, the most celebrated and awarded gaming mouse in the world has earned its popularity through its exceptional ergonomic design',
            },
        ],
        "Mobiles":[
            {
                id:'Mobiles_1',
                title: 'Google Pixel 4a',
                rating: 5,
                img: 'https://fdn2.gsmarena.com/vv/pics/google/google-pixel-4a-1.jpg',
                price: 799,
                inStock: true,
                keywords: 'mobiles mobile phones phones mobilephones mobilephone',
                description: 'Meet Pixel 4a, the helpful Google phone at a helpful price. It comes packed with the things you want most in a phone, like a camera that takes great low-light photos',
            },
            {
                id:'Mobiles_2',
                title: 'OnePlus Nord N100',
                rating: 5,
                img: 'https://oasis.opstatics.com/content/dam/oasis/page/billie/N100-Frame.png',
                price: 179,
                inStock: false,
                keywords: 'mobiles mobile phones phones mobilephones mobilephone',
                description: 'OnePlus Nord N100 comes with a big display, big battery, and big storage at an affordable price. It sports a 6.52” immersive display with the power of dual stereo speakers',
            },
            {
                id:'Mobiles_3',
                title: 'Samsung Galaxy S21',
                rating: 4,
                img: 'https://fdn.gsmarena.com/imgroot/news/20/12/samsung-galaxy-s21-renders/-1200/gsmarena_004.jpg',
                price: 699,
                inStock: true ,
                keywords: 'mobiles mobile phones phones mobilephones mobilephone',
                description: 'Life is a series of moments. Why not make them beautiful? Take your photos and videos to an incredible new level with multiple, cutting-edge ways to capture life exactly as it is',
            },
            {
                    id:'Mobiles_4',
                    title: 'OnePlus 8 Pro Onyx',
                    rating: 5,
                    img: 'https://images-na.ssl-images-amazon.com/images/I/61YSMhOd5EL._SX679_.jpg',
                    price: 899,
                    inStock: true ,
                    keywords: 'mobiles mobile phones phones mobilephones mobilephone',
                    description: 'OnePlus 8 Pro Onyx Black,? 5G Unlocked Android Smartphone U.S Version, 12GB RAM+256GB Storage, 120Hz Fluid Display,Quad Camera, Wireless Charge, with Alexa Built-in',

            },
            {
                    id:'Mobiles_5',
                    title: 'Nokia 3.4',
                    rating: 4,
                    img: 'https://fdn2.gsmarena.com/vv/pics/nokia/nokia-34-2.jpg',
                    price: 169,
                    inStock: true ,
                    keywords: 'mobiles mobile phones phones mobilephones mobilephone',
                    description: 'Upgrade to more phone and more power with Nokia 3.4. Maximize your streaming, binging and work on a 6.39-inch HD+ screen--with punch hole display that gives you even more screen real estate. Dont sweat running out of juice with 2-day battery life.'
            },
            {
                    id:'Mobiles_6',
                    title: 'Samsung Galaxy A10s',
                    rating: 5,
                    img: 'https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-a10s-1.jpg',
                    price: 131,
                    inStock: true ,
                    keywords: 'mobiles mobile phones phones mobilephones mobilephone',
                    description: 'Built for ImmersionA 15.79cm (6.2) HD+ immersive screen with an Infinity-V display that lets you binge-watch at ease and level-up your gaming.'
            },
            {
                    id:'Mobiles_7',
                    title: 'Samsung Galaxy S20',
                    rating: 5,
                    img: 'https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s20-5g-r1.jpg',
                    price: 59,
                    inStock: true ,
                    keywords: 'mobiles mobile phones phones mobilephones mobilephone',
                    description: 'We get you. The standout in the crowd, the one with relentless passion. The one that stays true to yourself and connected to those around you.'
            },
            {
                    id:'Mobiles_8',
                    title: 'OnePlus 8T',
                    rating: 5,
                    img: 'https://fdn2.gsmarena.com/vv/pics/oneplus/oneplus-8t-lunar.jpg',
                    price: 599,
                    inStock: true ,
                    keywords: 'mobiles mobile phones phones mobilephones mobilephone',
                    description: '5G Unlocked Android Smartphone U.S Version, 12GB RAM+256GB Storage, 120Hz Fluid Display,Quad Camera, 65W Ultra Fast Charge, Lunar Silver, U.S Warranty'
            }
        ]
    }